### ISSUE TITLE
Add support for Test Guidance G4

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-php#109]
Add support for the following requirements: G4

As stated at https://docs.ably.io/client-lib-development-guide/features/#G4

see details https://github.com/ably/docs/blob/main/content/client-lib-development-guide/versions/features-1-1__1-2.diff

Acceptance Criteria: 

Implement the support for the requirements above

Update the spreadsheet

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-1003) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
`G4` is implicitly complied with already.
