### ISSUE TITLE
Add support for PC1, PC2, PC3, PC3a (Plugins)

### ISSUE THREAD

**Issue by AndyNicks** [ably/ably-php#116]
Add support for the following requirements: PC1, PC2, PC3, PC3a
As stated at https://docs.ably.io/client-lib-development-guide/features/#PC1

see details https://github.com/ably/docs/blob/main/content/client-lib-development-guide/versions/features-1-1__1-2.diff

Acceptance Criteria: 

Implement the support for the requirements above

Update the spreadsheet

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-996) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
There is no need for plugins in this SDK. It was necessary only for JS due to limiting download size of the runtime in the web browser context.
