### ISSUE TITLE
Presence test is failing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#13]
@kouno see https://travis-ci.org/ably/ably-php

Can you fix the error so that this library is passing again?

**Comment by mattheworiordan** [comment]
Another auth request is now failing https://travis-ci.org/ably/ably-php, @kouno can you look into it please?

**Comment by mattheworiordan** [comment]
I think the auth request is most likely an issue with our sandbox environment having issues in us-east-1.  I will rerun the tests.  The presence test is dependent upon https://github.com/ably/realtime/issues/164 to be resolved.

**Comment by kouno** [comment]
The build is passing. At least we will see when the tests break but I marked the test as incomplete while we resolve https://github.com/ably/realtime/issues/164.

**Comment by mattheworiordan** [comment]
I am not sure we should close this issue as we should check once #164 is resolved no?

**Comment by kouno** [comment]
When 164 is fixed, we will have to update all client libraries anyway. If you leave that one open, does that mean that each client library should have one issue related to 164?

**Comment by mattheworiordan** [comment]
Well not necessarily, it's just that this client libraries implementation of paging made assumptions about the presence of the header, as did Ruby, so other client libs are not necessarily effected.

**Comment by kouno** [comment]
> so other client libs are not necessarily effected.

"not necessarily" means that we will have to crosscheck every one of them anyway.

I think it's just a lot of noise, but if you insist, we can keep that one open.
