### ISSUE TITLE
Switch arity of auth methods

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#16]
See https://github.com/ably/docs/commit/63ff7fa2d654641a9d7856bd8dc67beb937d3fef

The `AuthOptions` and `TokenParams` arguments are switched.

**Comment by mattheworiordan** [comment]
@bladeSk is this implemented?  Can we close this issue?

**Comment by bladeSk** [comment]
Actually it wasn't. It is now - https://github.com/bladeSk/ably-php/commit/f1d872a0733e413214e371294f6560735fe4b2a9 & https://github.com/bladeSk/ably-php/commit/702fd650115101a99364a401e9f0e874b710e367

**Comment by mattheworiordan** [comment]
Ah, good.  I wonder if perhaps it may be worth, as a final step, to simply run through the tests and the spec to make sure there are no other changes that have slipped through?
