### ISSUE TITLE
0.8.x finalisation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#20]
@bladeSk, we have a few minor **final** changes to the spec to resolve some unaddressed points and reduce ambiguity in the spec.

See https://docs.google.com/spreadsheets/d/1bG_SEVlCi3blQBveGtsncxFGD4ArCtS-JCq6iLW3lGw/edit#gid=2047058158&vpid=B4 for the list of changes, which includes references to all spec items that have changed.

Can you please go through all of those and ensure all items in the unified spec are covered by your tests and documented in the unified spec doc?

**Comment by mattheworiordan** [comment]
When these changes are all merged in, please tag a new version and update the CHANGELOG, and then ensure we distribute this package

**Comment by bladeSk** [comment]
Sure.

I can't tag a new version in this repo, PRs don't include tags. So either you'll have to create a tag or I'll need write access to this repo.

**Comment by mattheworiordan** [comment]
Ah thought you had access to the repo. Shout when you want me to add a tag. Or I cangive you write access, as you prefer?

**Comment by bladeSk** [comment]
Done!
