### ISSUE TITLE
[Question] Does ably-php support Queues

### ISSUE THREAD

**Issue by g41797** [ably/ably-php#200]
Context:
 I am developing [set of queue libraries](https://github.com/g41797/queue/blob/master/docs/guide/en/adapter-list.md) for [Yii PHP Framework](https://www.yiiframework.com/).

[Ably Queues](https://ably.com/docs/general/queues) look as promising addition.

Question:
 **Does ably-php support Queues?**

Thanks

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4876) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
As per documentation https://ably.com/docs/general/queues, Ably queues can be accessed using either `AMQP` or `STOMP` protocols. `ably-php` used native ably protocol and provides pub-sub functionality ( has nothing to do with ably queues as such ).
You might like to look at https://github.com/php-amqp/php-amqp to connect with ably queues.

**Comment by sacOO7** [comment]
![image](https://github.com/user-attachments/assets/77c5f9a4-6147-4cb3-a10f-3a99f8854af0)

**Comment by g41797** [comment]
does it mean that i can use ready rabbitmq amqp client to work with ably?

**Comment by sacOO7** [comment]
As long as it uses AMQP protocol, yes
