### ISSUE TITLE
Travis version support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#21]
@bladeSk as you have added PHP 7 support, I think it's important that our test suite runs against multiple versions.  If you look at https://github.com/ably/ably-php/blob/master/.travis.yml#L3, you will see we only support 5.4 now.  Should we not run the test suite against all support PHP versions to make sure we don't introduce regressions in future?

See https://docs.travis-ci.com/user/languages/php/

**Comment by bladeSk** [comment]
Done
