### ISSUE TITLE
Do not persist authorise attributes force & timestamp 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#23]
A recent discovery in the iOS library has unearthed a small shortcoming in the spec, corrected at https://github.com/ably/docs/commit/f768f0db76020d945cf34974ef7d14d36113f0cd

**Comment by bladeSk** [comment]
moved the `0.8.2` tag to the latest commit that fixes this + updated packagist

**Comment by mattheworiordan** [comment]
Thanks @bladeSk but in future we should not move tags, but instead simply create a new version as now it is possible that two people may have different code for a `0.8.2` install
