### ISSUE TITLE
Mac mismatch - possible timezone issue?

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#26]
A customer, when using the following auth code, gets "Request mac does not match"

```php
$subscriberClient = new \Ably\AblyRest(array(
  'key' => $this->subscribeApiKey
));
$tokenDetails = $subscriberClient->auth->requestToken(array(), array(
  'queryTime' => false
));
```

However, when changing `queryTime` to true, the error goes away.

```php
$subscriberClient = new \Ably\AblyRest(array(
  'key' => $this->subscribeApiKey
));
$tokenDetails = $subscriberClient->auth->requestToken(array(), array(
  'queryTime' => true
));
```

I checked with the customer, and it seems their local time was within at most a second of the actual time, so I suspect this could be a timezone issue.  They are in France, so GMT +1.

I asked them to do the following:

> In one console, do:
> php -a
> echo microtime(true);
> and then in another window, at around the same time! do the following:
> $ curl rest.ably.io/time
> What is the difference in values ignoring the part of the decimal

> Customer: 
> PHP : 1455545827.01
> CURL : 1455545827562

**Comment by mattheworiordan** [comment]
From @bladeSk on the issue:

> Hmm, I can't get it not to work. I'm in the same time zone and tried both Windows and a Debian server.
> So in order to understand what's going on with the hmac generation, I think we'll need to see the "signText". The easiest way of dumping that is putting `var_dump($signText);` here https://github.com/ably/ably-php/blob/master/src/Auth.php#L320
> It could possibly have something to do with a 32 bit version of PHP. Although I can't imagine why they'd have that.

**Comment by frankie567** [comment]
Hi there,

I'm the customer in question, from ProTournoi. Here is the result of the `var_dump($signText);` :
`string(67) "llk17g.ICsvtg 1.4556315941E+12 057429a11d26f71da9e02bb063f17e1c "`

Regards !

**Comment by bladeSk** [comment]
Ah, I see what the problem is. The timestamp got converted to float and printed with exponent, which is obviously a very different string than you'd get by printing an integer.
@frankie567 Could you please check what version of PHP you are running by running this from your shell?
`php -r "echo PHP_VERSION.' '.PHP_OS.' '.(PHP_INT_SIZE*8).'bit '.PHP_INT_MAX;"`

**Comment by frankie567** [comment]
Here it is :
`5.6.10 Darwin 64bit 9223372036854775807`

**Comment by bladeSk** [comment]
Thanks. This looks like incosistency with PHP's handling of numbers across platforms. I should have a fix ready tomorrow.

**Comment by mattheworiordan** [comment]
Thanks @bladeSk

**Comment by bladeSk** [comment]
Fixed here https://github.com/ably/ably-php/pull/28
