### ISSUE TITLE
Add Laravel support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#33]
Seeing questions like http://stackoverflow.com/questions/37854005/laravel-event-broadcast-not-work-with-pusher, I can see that deeper integration with a framework such as Laravel would be advantageous.

We should consider this.

**Comment by bladeSk** [comment]
We have a Laravel wrapper now: https://github.com/ably/ably-php-laravel

**Comment by sacOO7** [comment]
Update :
We released a better solution ->  https://github.com/ably/laravel-broadcaster. It covers every aspect of `laravel-broadcasting`.
