### ISSUE TITLE
Add support for remembered REST fallback host 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-php#60]
See https://github.com/ably/docs/pull/554

We need to add this functionality to all client libraries, but prioritise the server-side ones given they are more affected if a single DC is offline and they are publishing at a high rate.

**Comment by mattheworiordan** [comment]
@jdavid can you look at this soon?

**Comment by jdavid** [comment]
This was already done in PR#67 and released in 1.1.0
