### ISSUE TITLE
Need to support Push payloads in  publish()

### ISSUE THREAD

**Issue by tomczoink** [ably/ably-php#82]
Per https://docs.ably.io/client-lib-development-guide/features/#RSL6a2

a Message can have extras: { push: { ... }} when published, but the library just silently discards it right now.

**Comment by mattheworiordan** [comment]
@jdavid is this something you can look at?

**Comment by mattheworiordan** [comment]
Seems a few spec items are not addressed that were updated in 1.1 for push support, including https://docs.ably.io/client-lib-development-guide/features/#RSL1h, https://docs.ably.io/client-lib-development-guide/features/#TM2i, https://docs.ably.io/client-lib-development-guide/features/#TP3i. 

@jdavid please ensure if any of these issues are not addressed in the Python lib that you create an issue there too.

**Comment by mattheworiordan** [comment]
@jdavid apart from 4a89a52, are you able to:

a) confirm status of this for Python
b) confirm that https://github.com/ably/ably-php/issues/82#issuecomment-537694107 is addressed or not?

**Comment by mattheworiordan** [comment]
Ok, great, do you agree we can close this then?

**Comment by jdavid** [comment]
Yes, I've reviewed TM2 and TP3 in ably-python, added extras to PressenceMessage (TP3i)

Closing
