### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by yigitsayan** [ably/ably-php#88]
Do you have any plans to support PHP 8.0? I'm getting the following issue when I try to install this package via composer
`ably/ably-php[1.1.0, ..., 1.1.3] require php ^5.6 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.`

**Comment by markcoxsmith** [comment]
Hi @yigitsayan , Will check this with our product team and get back to you

**Comment by markcoxsmith** [comment]
Hi @yigitsayan , This is in our roadmap but we don't have an exact time yet. In January we will have a better understanding of when this can be implemented

**Comment by yigitsayan** [comment]
Thank you for the info @markcoxsmith looking forward to PHP 8.0 support!

**Comment by floriangaerber** [comment]
Hi @markcoxsmith, 
I have a draft PR for PHP 8 support here: https://github.com/floriangaerber/ably-php/pull/1/

Apart from 2 tests that are already failing on the main branch, and some issue with `ChannelIdempotentTest::testIdempotentLibraryGenerated`, ably-php seems to be compatible with PHP 8 without any changes to the library.

**Comment by markcoxsmith** [comment]
Hi @floriangaerber , 
Thanks so much for this and will mention pass this on to our SDK team.
