### ISSUE TITLE
Batch Mode, sending multiple messages to multiple channels

### ISSUE THREAD

**Issue by carbontwelve** [ably/ably-php#98]
I am aware that batch message sending is still a "beta" feature of the REST api, and am also aware that this library does current'y seem to support usage of batch mode when sending multiple messages to the same channel.

However it would be very useful if it provided a batch helper for sending different messages to different channels all within one Api call.

**Comment by owenpearson** [comment]
Hi @carbontwelve. You can send different messages to different channels in a batch publish by sending an array of `BatchSpec` objects in the request body. See the "Using multiple BatchSpec objects in an array" section [here](https://ably.com/documentation/rest-api/beta#batch-publish). I hope this helps.
